"""initial schema

Revision ID: 897ddd63b320
Revises: 
Create Date: 2025-04-10 14:39:17.206155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '897ddd63b320'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
